### ISSUE TITLE
Upload all the files of this respository here in this repository

### ISSUE THREAD

**Issue by ViorelEremia** [NicoRachiu/Gallery#1]
Mention this issue in the commit. How to do this try to read and test these articles of google: https://www.google.com/search?q=mention+a+issue+in+the+commit+github&oq=mention+a+issue+in+the+commit+github&aqs=chrome..69i57j33i10i160l2.9003j0j7&sourceid=chrome&ie=UTF-8

**Comment by NicoRachiu** [comment]
How can I copy all files from this repository to a repository that doesn't exist?

**Comment by NicoRachiu** [comment]
I can't mention the issue in the commit because I had already added the files in the repo

**Comment by ViorelEremia** [comment]
Ok, when mention the commit hash here in the comments and close the issue

**Comment by NicoRachiu** [comment]
To mention an issue you simply have to add at the end of a commit's name: #The_issue_number

**Comment by NicoRachiu** [comment]
[https://github.com/NicoRachiu/Gallery/commit/c7838e805286894b63d485c805b4f70290d3df88](https://github.com/NicoRachiu/Gallery/commit/c7838e805286894b63d485c805b4f70290d3df88?fbclid=IwAR1iDbjyLvQebwiI7faqaiQcdua7XJhPbpex02HsBqXo3QAnZ1khsDagrLE)
